# â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
# Super-Linter GitHub Actions Workflow
# â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
#
# ğŸš€ Combination of multiple linters to run as a GitHub Action - includes
#    actionlint for GitHub Actions and markdownlint for Markdown files.
#
# ğŸ“š Resources:
#    â€¢ Documentation: https://github.com/super-linter/super-linter
#    â€¢ Marketplace:   https://github.com/marketplace/actions/super-linter
#    â€¢ Configuration: https://github.com/super-linter/super-linter#environment-variables
#
# ğŸ’» Run locally:
#    docker run --platform=linux/amd64 \
#      -e LOG_LEVEL=DEBUG \
#      -e RUN_LOCAL=true \
#      -v "$(git rev-parse --show-toplevel)":/tmp/lint \
#      ghcr.io/super-linter/super-linter:latest
#
# â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•

name: Super-Linter

on: [push, pull_request]

# Ensure top-level permissions are not set to write-all.
permissions: {}

jobs:
  super-lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks.
      statuses: write
    steps:
      - uses: actions/checkout@v5
        with:
          # The super-linter needs the full git history to get the
          # list of files that changed across commits.
          fetch-depth: 0
      - uses: super-linter/super-linter@v8
        env:
          # To report GitHub Actions status checks.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
